version: '3.8'

services:
  lenovo-tracker:
    container_name: lenovo-india-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
